### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Nindainell** [HormyAJP/pam_sqlite3#4]
I happen to not found the dependencies you need in the README section, if someone has the same isue there they are: **libsqlite3-dev libpam0g-dev**

**Comment by q2dg** [comment]
That's for Ubuntu. For Fedora dependencies are **sqlite-devel** and **pam-devel** (besides **sqlite**, of course)

**Comment by q2dg** [comment]
Done by https://github.com/HormyAJP/pam_sqlite3/pull/9
