### ISSUE TITLE
Wish: would it be possible to store (and retrieve) password in SHA-512 (in addition to plain, md5 and crypt)?

### ISSUE THREAD

**Issue by q2dg** [HormyAJP/pam_sqlite3#7]
To be on pair with current, modern hash login standards
Thanks!

**Comment by HormyAJP** [comment]
@q2dg I didn't see your issues as I didn't have notifications configured 🤕 

I've made you a contributor. Please feel free to raise pull requests and I'll review. I won't have time just at the moment to fix issues but will try in the coming weeks if you don't raise PRs yourself.

Thanks,
Andrew

**Comment by q2dg** [comment]
Thanks a lot for your trust
I don't have the necessary skills right now but I'll try to study and understand your code and the PAM infrastructure. I'll try to do my best...I hope I can.
Thanks a lot again

**Comment by q2dg** [comment]
Solved by https://github.com/HormyAJP/pam_sqlite3/pull/8
